simulating:
  logPercent: 0.1
  matrixLenX: 1000
  matrixLenY: 1000
  floatPrecision: 8
  graphicsToPlot:
    - xAxis: Simulation time
      yAxis: Surface coverage
    - xAxis: Simulation time
      yAxis: Density F
    - xAxis: Simulation time
      yAxis: Density S
  stopOnQuasiSteady: true
  requiredStableChecks: 10
  checkParameters:
    - name: densityF
      tolerance: 2
      valuesWindowSize: 100
schemePath: configs/scheme_marinov.yaml
consts:
  fDensity: 1500000000000000
  fi: 0.002
  sDensity: 3000000000000
elements:
  - name: "N"
    mass: 14
    edes: 51000
    edif: 25500
    vdes: 1000000000000000
    vdif: 10000000000000
    er: 14000
    erlh: 0
    agDensity: 800000000000000
    sort: 1
